localaddr = ":8762"
resolveraddr = "[::1]:7777"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
externaladdr = "https://localhost:8762"
loglevel = "DEBUG"
jwtalg = ["HS256","HS384","HS512"]

[_jwtkey]
test = "geheimtest"
tests3 = "geheimtests3"
testcache = "geheimtestcache"


[webtls]
type = "minivault"
initialtimeout = "1h"
[webtls.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2221ba907909fc47.ce4f7702cc264bb8"
tokentype = "server_cert"
tokenpolicies = ["remotefs"]
certtype = "server_cert"
dnss = ["localhost"]
uris = []
ips = ["127.0.0.1", "::1"]
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[vfs.drivec]
name = "drivec"
type = "os"
[vfs.drivec.os]
basedir = "C:/Users/micro/Downloads"

[_vfs.test]
name = "test"
type = "sftp"
[_vfs.test.sftp]
address = "ub-x2go4.ub.p.unibas.ch:22"
user = "jumpuser"
privatekey = ["C:/daten/keys/syncthing/putty_ed25519.priv.openssh"]
basedir = "/digispace"
sessions = 3
zipasfoldercache = 2

[vfs.tests3]
name = "tests3"
type = "S3"
[vfs.tests3.S3]
AccessKeyID = "009145048a6e9c39de76"
SecretAccessKey = "%%TESTSECRET%%"
Endpoint = "s3-zh.lts.switch.ch"
Region = "zurich"
UseSSL = true
Debug = false
CAPEM = ""
BaseUrl = ""
ZipAsFolderCache = 0

[vfs.testcache]
name = "testcache"
type = "S3"
[vfs.testcache.S3]
AccessKeyID = "AKIA312912CB2F7328D3"
SecretAccessKey = "%%TESTCACHESECRET%%"
Endpoint = "vip-ecs-ub.storage.p.unibas.ch"
Region = ""
UseSSL = true
Debug = false
BaseUrl = ""
ZipAsFolderCache = 0
CAPEM = ""

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="remotefs"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
